"""
Persistence service for conjectural requirements and evaluations.

Saves DataContext conjectural data to the database and writes back
the generated UUIDs into the in-memory models.
"""

from app.agent.models.data_context import DataContext, ConjecturalRequirement, Evaluation
from app.services.supabase_client import get_supabase_client


def _build_requirement_row(project_id: str, group_index: int, cr: ConjecturalRequirement) -> dict:
    """Build a database row dict from a ConjecturalRequirement."""
    return {
        "project_id": project_id,
        "group_index": group_index,
        "attempt": cr.attempt,
        "ranking": cr.ranking,
        "status": "todo",
        "desired_behavior": cr.ferc.desired_behavior,
        "positive_impact": cr.ferc.positive_impact,
        "uncertainties": list(cr.ferc.uncertainties),
        "solution_assumption": cr.qess.solution_assumption,
        "uncertainty_evaluated": cr.qess.uncertainty_evaluated,
        "observation_analysis": cr.qess.observation_analysis,
    }


def _build_evaluation_row(requirement_db_id: str, eval_type: str, evaluation: Evaluation) -> dict:
    """Build a database row dict from an Evaluation."""
    return {
        "requirement_id": requirement_db_id,
        "type": eval_type,
        "unambiguous": evaluation.scores.get("unambiguous", 1),
        "completeness": evaluation.scores.get("completeness", 1),
        "atomicity": evaluation.scores.get("atomicity", 1),
        "verifiable": evaluation.scores.get("verifiable", 1),
        "conforming": evaluation.scores.get("conforming", 1),
        "justifications": evaluation.justifications,
    }


def persist_conjectural_data(project_id: str, data_context: DataContext) -> None:
    """Persist all conjectural requirements and evaluations to the database.

    After insertion, each ConjecturalRequirement.db_id is updated with the
    UUID generated by the database.
    """
    supabase = get_supabase_client()

    for group_index, cd in enumerate(data_context.conjectural_data):
        for cr in cd.conjectural_requirements:
            # Insert conjectural requirement
            row = _build_requirement_row(project_id, group_index, cr)
            result = supabase.table("conjectural_requirements").insert(row).execute()

            if not result.data:
                print(f"[Persistence] Failed to insert requirement group={group_index} attempt={cr.attempt}")
                continue

            db_id = result.data[0]["id"]
            cr.db_id = db_id
            print(f"[Persistence] Saved requirement group={group_index} attempt={cr.attempt} → {db_id}")

            # Insert evaluations
            eval_rows = []
            if cr.llm_evaluation and cr.llm_evaluation.scores:
                eval_rows.append(_build_evaluation_row(db_id, "llm", cr.llm_evaluation))
            if cr.human_evaluation and cr.human_evaluation.scores:
                eval_rows.append(_build_evaluation_row(db_id, "human", cr.human_evaluation))

            if eval_rows:
                supabase.table("evaluations").insert(eval_rows).execute()
                print(f"[Persistence] Saved {len(eval_rows)} evaluation(s) for requirement {db_id}")
