"""
Knowledge Graph models and NetworkX helpers.

Provides Pydantic models for domain entities and their relationships,
along with serialization helpers for LangGraph state and NetworkX interop.
"""

from typing import Any, Dict, List, Literal

import networkx as nx
from pydantic import BaseModel, Field


class EntityNode(BaseModel):
    """A node in the knowledge graph: a domain entity with its meaning."""

    entity: str = Field(description="The domain entity name")
    meaning: str = Field(description="The definition/meaning of the entity")
    source: Literal["extracted", "inferred"] = Field(
        description="Origin of the meaning: 'extracted' (Known Known, from documents) "
        "or 'inferred' (Unknown Known, via stakeholder persona simulation)"
    )
    is_ambiguous: bool = Field(
        default=False,
        description="Whether this entity was identified as ambiguous (subjective/vague term)"
    )


class EntityRelation(BaseModel):
    """An edge in the knowledge graph: a relationship between two entities."""

    source: str = Field(description="Source entity name")
    target: str = Field(description="Target entity name")
    relation: str = Field(description="Type of relationship (e.g., 'uses', 'depends on')")


class BusinessUncertainty(BaseModel):
    """An uncertainty linked to a business need."""

    business_need: str = Field(description="The business need statement")
    uncertainty: str = Field(description="The key uncertainty associated with this business need")


class KnowledgeGraph(BaseModel):
    """Domain knowledge graph produced by the elicitation node."""

    nodes: List[EntityNode] = Field(default_factory=list)
    edges: List[EntityRelation] = Field(default_factory=list)
    stakeholder: str = Field(default="end user", description="Primary stakeholder identified")
    domain: str = Field(default="general software", description="Project domain identified")
    project_summary: str = Field(default="", description="Concise project summary used as context for downstream analysis")
    business_objective: str = Field(default="", description="Main business goal or value proposition the project aims to achieve")
    business_needs: List[str] = Field(
        default_factory=list,
        description="Business needs derived from the project vision and requirements"
    )
    business_uncertainties: List[BusinessUncertainty] = Field(
        default_factory=list,
        description="Uncertainties linked to business needs"
    )
    ambiguous_terms: List[str] = Field(
        default_factory=list,
        description="List of entity names identified as ambiguous by the analysis node"
    )
    non_ambiguity_metric: float = Field(
        default=1.0,
        description="Ratio of non-ambiguous terms to total terms (0.0 to 1.0)"
    )
    conjectural_requirements: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Conjectural requirements generated by the specification node, serialized as dicts (FERC + QESS)"
    )


def to_networkx(kg: KnowledgeGraph) -> nx.DiGraph:
    """Convert a KnowledgeGraph Pydantic model to a NetworkX DiGraph."""
    G = nx.DiGraph()

    for node in kg.nodes:
        G.add_node(node.entity, meaning=node.meaning, source=node.source, is_ambiguous=node.is_ambiguous)

    for edge in kg.edges:
        G.add_edge(edge.source, edge.target, relation=edge.relation)

    G.graph["stakeholder"] = kg.stakeholder
    G.graph["domain"] = kg.domain
    G.graph["project_summary"] = kg.project_summary
    G.graph["ambiguous_terms"] = kg.ambiguous_terms
    G.graph["non_ambiguity_metric"] = kg.non_ambiguity_metric

    return G


def from_networkx(G: nx.DiGraph) -> KnowledgeGraph:
    """Convert a NetworkX DiGraph back to a KnowledgeGraph Pydantic model."""
    nodes = [
        EntityNode(
            entity=n,
            meaning=data.get("meaning", ""),
            source=data.get("source", "extracted"),
            is_ambiguous=data.get("is_ambiguous", False),
        )
        for n, data in G.nodes(data=True)
    ]
    edges = [
        EntityRelation(source=u, target=v, relation=data.get("relation", ""))
        for u, v, data in G.edges(data=True)
    ]
    return KnowledgeGraph(
        nodes=nodes,
        edges=edges,
        stakeholder=G.graph.get("stakeholder", "end user"),
        domain=G.graph.get("domain", "general software"),
        project_summary=G.graph.get("project_summary", ""),
        ambiguous_terms=G.graph.get("ambiguous_terms", []),
        non_ambiguity_metric=G.graph.get("non_ambiguity_metric", 1.0),
    )


def kg_to_state(kg: KnowledgeGraph) -> Dict[str, Any]:
    """Serialize a KnowledgeGraph to a dict for LangGraph state."""
    return kg.model_dump()


def kg_from_state(data: Dict[str, Any]) -> KnowledgeGraph:
    """Reconstruct a KnowledgeGraph from a LangGraph state dict."""
    return KnowledgeGraph.model_validate(data)
