"""
Validation Node - Validate the conjectural requirement specification.

This node evaluates the conjectural requirements generated by the Specification
node, scoring each one from 1 to 10 based on quality criteria.
"""

import json
from typing import Optional

from langchain_core.runnables.config import RunnableConfig
from langchain_core.messages import AIMessage, HumanMessage, ToolMessage
from langchain_core.tools import tool
from app.agent.llm_config import get_model, extract_text, DEFAULT_GEMINI_MODEL, DEFAULT_AZURE_OPENAI_JUDGE_MODEL
from langgraph.types import Command, interrupt
from copilotkit.langgraph import copilotkit_customize_config, copilotkit_emit_state, copilotkit_emit_message

from app.agent.state import WorkflowState
from app.agent.models.data_context import DataContext, Evaluation
from app.agent.utils.context_utils import extract_copilotkit_context
from app.agent.utils.project_data import language_instruction
from app.services.conjectural_persistence import persist_conjectural_data


@tool
def show_requirements(requirement_ids: str):
    """Tool function to show requirements on the frontend board."""
    return {"success": True}


VALIDATION_SYSTEM_PROMPT = """You are a rigorous and demanding expert evaluator of conjectural software requirements. \
Your role is to critically assess the quality of each requirement with high standards. \
Do not be lenient — a score of 5 (Very Good) should only be given when the criterion is fully and unambiguously satisfied.

A conjectural requirement consists of two parts:
- **FERC** (Writing Format for Conjectural Requirements): describes the desired system behavior, its positive impact, and the associated uncertainties.
- **QESS** (Solution Assumption Experimentation Framework): describes a solution assumption, the single uncertainty it will evaluate, and how the evaluation will be performed.

Evaluate the following conjectural requirement on a Likert scale from **1 to 5** for each of the five quality criteria below:

1. **Unambiguous** — Is the requirement written in a way that can only be interpreted in one way? Are there vague terms, ambiguous pronouns, or imprecise language?
2. **Completeness** — Does the requirement contain all necessary information (desired behavior, positive impact, uncertainties, solution assumption, observation method)? Are there missing details?
3. **Atomicity** — Does the requirement describe exactly one behavior or concern? Could it be split into multiple independent requirements?
4. **Verifiable** — Can the requirement be objectively tested or verified? Is there a clear criterion for determining whether it has been satisfied?
5. **Conforming** — Does the requirement correctly follow the FERC/QESS structure and conventions? Is the QESS coherent with the FERC uncertainties?

**Likert scale:**
- 1 = Very Poor
- 2 = Poor
- 3 = Regular
- 4 = Good
- 5 = Very Good

**Rules:**
- For any score from 1 to 4, you MUST provide a justification explaining why the criterion was not fully met.
- For a score of 5, justification is optional (leave as empty string if not needed).
- Be strict and objective. Favor lower scores when in doubt.

**Project context:**
- Summary: {project_summary}
- Domain: {domain}
- Primary stakeholder: {stakeholder}

**Conjectural Requirement #{requirement_number}:**

[FERC]
- Desired behavior: {desired_behavior}
- Positive impact: {positive_impact}
- Uncertainties: {uncertainties}

[QESS]
- Solution assumption: {solution_assumption}
- Uncertainty evaluated: {uncertainty_evaluated}
- Observation & analysis: {observation_analysis}

**Respond with ONLY a valid JSON object** in the following format (no markdown, no extra text):
{{
  "scores": {{
    "unambiguous": <1-5>,
    "completeness": <1-5>,
    "atomicity": <1-5>,
    "verifiable": <1-5>,
    "conforming": <1-5>
  }},
  "justifications": {{
    "unambiguous": "<justification or empty string>",
    "completeness": "<justification or empty string>",
    "atomicity": "<justification or empty string>",
    "verifiable": "<justification or empty string>",
    "conforming": "<justification or empty string>"
  }}
}}
"""


async def validation_node(state: WorkflowState, config: Optional[RunnableConfig] = None):
    """
    Validate the conjectural requirement specification.

    1. Retrieves the conjectural requirements from the knowledge graph
    2. Calls the LLM to evaluate each requirement on a scale of 1 to 10
    3. Adds the evaluation response to the messages list
    """
    config = copilotkit_customize_config(config, emit_messages=False)

    if config is None:
        config = RunnableConfig(recursion_limit=25)

    print("Validation node started.")
    messages = state.get("messages", [])

    data_context = DataContext.model_validate(state.get("data_context", {}))

    context = extract_copilotkit_context(state)
    require_evaluation = context['require_evaluation']

    # --- Step 1: Human evaluation (interrupt) ---
    if require_evaluation:
        # Build requirements list for frontend interrupt
        requirements_list = []
        for i, cd in enumerate(data_context.conjectural_data):
            if not cd.conjectural_requirements:
                continue
            cr = cd.conjectural_requirements[-1]
            requirements_list.append({
                "requirement_number": i + 1,
                "attempt": cr.attempt,
                "desired_behavior": cr.ferc.desired_behavior,
                "positive_impact": cr.ferc.positive_impact,
                "uncertainties": "; ".join(cr.ferc.uncertainties),
                "solution_assumption": cr.qess.solution_assumption,
                "uncertainty_evaluated": cr.qess.uncertainty_evaluated,
                "observation_analysis": cr.qess.observation_analysis,
            })

        print(f"[Validation] Sending {len(requirements_list)} requirements for human evaluation via interrupt")
        human_evaluation_response = interrupt({
            "type": "hitl_req_approve",
            "requirements": requirements_list,
        })

        # Parse and store human evaluation data
        try:
            eval_data = json.loads(human_evaluation_response) if isinstance(human_evaluation_response, str) else human_evaluation_response
            evaluations = eval_data.get("evaluations", {})
            print(f"[Validation] Human evaluation received for {len(evaluations)} requirements:")

            for req_number_str, evaluation in evaluations.items():
                cd_index = int(req_number_str) - 1
                if cd_index < len(data_context.conjectural_data):
                    human_eval = Evaluation.model_validate(evaluation)
                    human_eval.compute_overall_score()
                    data_context.conjectural_data[cd_index].conjectural_requirements[-1].human_evaluation = human_eval

            state["data_context"] = data_context.model_dump()
            await copilotkit_emit_state(config, state)

            for req_number_str, evaluation in evaluations.items():
                human_eval = Evaluation.model_validate(evaluation)
                print(f"  Requirement #{req_number_str}:")
                for criterion, score in human_eval.scores.items():
                    justification = human_eval.justifications.get(criterion, "")
                    justification_info = f' — "{justification}"' if justification else ""
                    print(f"    {criterion}: {score}/5{justification_info}")
        except Exception as e:
            print(f"[Validation] Error parsing human evaluation response: {e}")
            print(f"[Validation] Raw response: {human_evaluation_response}")

    elif not require_evaluation:
        print("[Validation] Human evaluation not required — skipping interrupt.")
    else:
        print("[Validation] Resuming after interrupt — human evaluation already completed.")

    # --- Step 2: LLM-as-Judge evaluation ---
    context = extract_copilotkit_context(state)
    model_judge_provider = context.get("model_judge", "gemini")
    print(f"[Validation] Starting LLM-as-Judge evaluation (provider: {model_judge_provider}) for {len(data_context.conjectural_data)} requirements...")
    judge_model_name = DEFAULT_GEMINI_MODEL if model_judge_provider == "gemini" else DEFAULT_AZURE_OPENAI_JUDGE_MODEL
    model = get_model(provider=model_judge_provider, model=judge_model_name)
    for i, cd in enumerate(data_context.conjectural_data):
        req_num = i + 1

        if not cd.conjectural_requirements:
            print(f"[Validation] Skipping #{req_num} — no conjectural requirements.")
            continue

        cr = cd.conjectural_requirements[-1]
        print(f"[Validation] LLM evaluating requirement #{req_num} (attempt {cr.attempt})...")

        prompt = VALIDATION_SYSTEM_PROMPT.format(
            project_summary=data_context.project_summary,
            domain=data_context.domain,
            stakeholder=data_context.stakeholder,
            requirement_number=req_num,
            desired_behavior=cr.ferc.desired_behavior,
            positive_impact=cr.ferc.positive_impact,
            uncertainties="; ".join(cr.ferc.uncertainties),
            solution_assumption=cr.qess.solution_assumption,
            uncertainty_evaluated=cr.qess.uncertainty_evaluated,
            observation_analysis=cr.qess.observation_analysis,
        ) + language_instruction(data_context.language)

        try:
            response = await model.ainvoke([HumanMessage(content=prompt)])
            raw_content = extract_text(response.content)
            eval_result = json.loads(raw_content)
            llm_eval = Evaluation.model_validate(eval_result)
            llm_eval.compute_overall_score()
            cr.llm_evaluation = llm_eval
            print(f"[Validation] Requirement #{req_num} evaluated (overall: {llm_eval.overall_score}/5):")
            for criterion, score in llm_eval.scores.items():
                justification = llm_eval.justifications.get(criterion, "")
                justification_info = f' — "{justification}"' if justification else ""
                print(f"    {criterion}: {score}/5{justification_info}")
        except Exception as e:
            print(f"[Validation] Error evaluating requirement #{req_num}: {e}")
            cr.llm_evaluation = Evaluation()

        state["data_context"] = data_context.model_dump()
        await copilotkit_emit_state(config, state)


    step4_validation = False
    pending_progress = True
    # se attempt = 3

    spec_attempts = context.get("spec_attempts", 3)
    if state.get("spec_attempt", 0) >= spec_attempts:
        data_context.rank_conjectural_requirements()

        # Persist to database and get generated UUIDs
        saved_ids = persist_conjectural_data(context["current_project_id"], data_context, context.get("current_user_id"))

        # message 1
        msg_created_text = "The following conjectural requirements were successfully **created**: " + ", ".join(saved_ids) + "."
        response = AIMessage(content=msg_created_text)
        messages = messages + [response]
        await copilotkit_emit_message(config, msg_created_text)

        # message 2
        # msg_ids_text = "\n".join(f"- {rid}" for rid in saved_ids)
        # response = AIMessage(content=msg_ids_text)
        # messages = messages + [response]
        # await copilotkit_emit_message(config, msg_ids_text)

        # message 3
        msg_graphic_text = "Below is an example of a chart for the first requirement generated. For more details on other requirements, go to the reports page."
        response = AIMessage(content=msg_graphic_text)
        messages = messages + [response]
        await copilotkit_emit_message(config, msg_graphic_text)

        # step4_validation is used in progress steps
        step4_validation = True
        pending_progress = False

        # --- Call show_requirements tool (must be LAST in messages) ---
        best_requirement_ids = []
        for entry in data_context.conjectural_data:
            for cr in entry.conjectural_requirements:
                if cr.ranking == 1 and cr.db_id:
                    best_requirement_ids.append(cr.db_id)

        model_with_tools = get_model(provider=context['model'], temperature=0)
        model_with_tools = model_with_tools.bind_tools([show_requirements, *state.get("tools", [])])

        tool_response = await model_with_tools.ainvoke(
            [
                HumanMessage(content=f"You ONLY should CALL show_requirements tool with requirement_ids: {json.dumps(best_requirement_ids)}"),
            ],
            config,
        )

        messages = messages + [tool_response]
        print("[Validation node] tool_response", tool_response)

        for tc in getattr(tool_response, "tool_calls", []) or []:
            print("[Validation node] tc=", tc)
            if tc["name"] == "show_requirements":
                result = show_requirements.invoke(tc["args"])
                print("[Validation node] result=", result)
                messages = messages + [
                    ToolMessage(content=json.dumps(result), tool_call_id=tc["id"])
                ]

    return Command(
        update={
            "messages": messages,
            "step1_elicitation": True,
            "step2_analysis": True,
            "step3_specification": True,
            "step4_validation": step4_validation,
            "pending_progress": pending_progress,
            "data_context": data_context.model_dump(),
        }
    )
