"""
Validation Node - Validate the conjectural requirement specification.

This node evaluates the conjectural requirements generated by the Specification
node, scoring each one from 1 to 10 based on quality criteria.
"""

import asyncio
from typing import Optional, List, Dict, Any

from langchain_core.runnables.config import RunnableConfig
from langchain_core.messages import AIMessage, HumanMessage
from app.agent.llm_config import get_model, extract_text
from langgraph.graph import END
from langgraph.types import Command
from copilotkit.langgraph import SystemMessage, copilotkit_emit_message, copilotkit_exit, copilotkit_customize_config, copilotkit_emit_state

from app.agent.state import WorkflowState
from app.agent.models.knowledge_graph import kg_from_state


VALIDATION_SYSTEM_PROMPT = """You are an expert evaluator of conjectural software requirements.

A conjectural requirement consists of two parts:
- **FERC** (Writing Format for Conjectural Requirements): describes the desired system behavior, its positive impact, and the associated uncertainties.
- **QESS** (Solution Assumption Experimentation Framework): describes a solution assumption, the single uncertainty it will evaluate, and how the evaluation will be performed.

Evaluate each conjectural requirement below on a scale from **1 to 10** based on the following criteria:
1. **Clarity** — Is the desired behavior clearly described?
2. **Relevance** — Is the requirement relevant to the project context (summary, domain, stakeholder)?
3. **Uncertainty quality** — Are the uncertainties genuine, specific, and measurable?
4. **QESS coherence** — Does the solution assumption directly address one of the listed uncertainties?
5. **Observability** — Is the proposed observation/analysis feasible and well-defined?

For each requirement, provide:
- A score from 1 to 10
- A brief justification (2–3 sentences) covering strengths and weaknesses

**Project context:**
- Summary: {project_summary}
- Domain: {domain}
- Primary stakeholder: {stakeholder}

**Conjectural requirements to evaluate:**
{conjectural_requirements}

Respond in natural language with a clear evaluation for each requirement.
End your response with:
1. The **overall average score** across all requirements.
2. The **conjectural requirement** exactly as received (reproducing the full FERC and QESS fields).
3. THE FINAL RESPONSE MUST BE EXACTLY AS FOLLOWS (including markdown syntax):

#### Conjectural Requirement #[number]

**Score: [score/10]**</br>
**Justification:** [description of justification]</br>

**FERC:**</br>
**It is expected that the software system has** [desired behavior]</br>
**So that** [need or positive impact of the desired attribute]</br>
**However, we do not know:**</br>
**Uncertainty:** [uncertainty associated with this requirement]</br>

**QESS:**</br>
**We expect that** [description of the solution assumption]</br>
**Will result in updating the uncertainties about** [the uncertainty that will be evaluated]</br>
**As a result of** [description of the observation and analysis that will result in updating the uncertainties]</br>

**Overall average score: [average score across all requirements]**
"""


def _format_conjectural_requirements(conjectural_requirements: List[Dict[str, Any]]) -> str:
    """Format serialized conjectural requirements for the validation prompt."""
    if not conjectural_requirements:
        return "No conjectural requirements available for validation."

    lines = []
    for i, cr in enumerate(conjectural_requirements, start=1):
        ferc = cr.get("ferc", {})
        qess = cr.get("qess", {})
        uncertainties = ferc.get("uncertainties", [])
        uncertainties_text = "\n".join(f"    - {u}" for u in uncertainties)

        lines.append(f"--- Conjectural Requirement #{i} ---")
        lines.append(f"[FERC] Desired behavior: {ferc.get('desired_behavior', '')}")
        lines.append(f"[FERC] Positive impact: {ferc.get('positive_impact', '')}")
        lines.append(f"[FERC] Uncertainties:\n{uncertainties_text}")
        lines.append(f"[QESS] Solution assumption: {qess.get('solution_assumption', '')}")
        lines.append(f"[QESS] Uncertainty evaluated: {qess.get('uncertainty_evaluated', '')}")
        lines.append(f"[QESS] Observation & analysis: {qess.get('observation_analysis', '')}")
        lines.append("")

    return "\n".join(lines)


async def validation_node(state: WorkflowState, config: Optional[RunnableConfig] = None):
    """
    Validate the conjectural requirement specification.

    1. Retrieves the conjectural requirements from the knowledge graph
    2. Calls the LLM to evaluate each requirement on a scale of 1 to 10
    3. Adds the evaluation response to the messages list
    """
    config = copilotkit_customize_config(config, emit_messages=True)

    if config is None:
        config = RunnableConfig(recursion_limit=25)

    print("Validation node started.")

    # --- Retrieve conjectural requirements from the knowledge graph ---
    kg = kg_from_state(state["knowledge_graph"])
    conjectural_requirements = kg.conjectural_requirements
    print(f"[Validation] Conjectural requirements to validate: {len(conjectural_requirements)}")

    # --- Build validation prompt ---
    prompt = VALIDATION_SYSTEM_PROMPT.format(
        project_summary=kg.project_summary,
        domain=kg.domain,
        stakeholder=kg.stakeholder,
        conjectural_requirements=_format_conjectural_requirements(conjectural_requirements),
    )

    model = get_model(temperature=0)

    messages = state.get("messages", [])

    try:
        response = await model.ainvoke([HumanMessage(content=prompt)])
        response.content = extract_text(response.content)
        print(f"[Validation] Evaluation completed.")
        print(f"[Validation] Response preview: {response.content[:200]}...")

    except Exception as e:
        print(f"Validation node error: {e}")
        response = AIMessage(content="I'm sorry, I encountered an error validating the conjectural requirements.")

    messages = messages + [response]

    state["step4_validation"] = True
    await copilotkit_emit_state(config, state)
    await asyncio.sleep(2)

    return Command(
        update={
            "messages": messages,
            "step1_elicitation": True,
            "step2_analysis": True,
            "step3_specification": True,
            "step4_validation": True,
            "pending_progress": False,
        }
    )
